{{- if and .Values.backend.enabled .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "goplan.backend.serviceAccountName" . }}
  namespace: {{ include "goplan.namespace" . }}
  labels:
    {{- include "goplan.backend.labels" . | nindent 4 }}
{{- end }}
