{{- if and .Values.frontend.enabled .Values.frontend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "goplan.frontend.serviceAccountName" . }}
  namespace: {{ include "goplan.namespace" . }}
  labels:
    {{- include "goplan.frontend.labels" . | nindent 4 }}
{{- end }}
