// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tasks": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "List tasks with optional filtering and pagination",
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "List all tasks",
                "parameters": [
                    {"type": "string", "description": "Search query", "name": "search", "in": "query"},
                    {"type": "string", "description": "Filter by status", "name": "status", "in": "query"},
                    {"type": "integer", "description": "Page number", "name": "page", "in": "query"},
                    {"type": "integer", "description": "Items per page", "name": "page_size", "in": "query"}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/TaskListResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "500": {"description": "Internal Server Error", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Create a new task with automatic similarity detection and prediction",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "Create a new task",
                "parameters": [
                    {"description": "Task to create", "name": "task", "in": "body", "required": true, "schema": {"$ref": "#/definitions/CreateTaskRequest"}}
                ],
                "responses": {
                    "201": {"description": "Created", "schema": {"$ref": "#/definitions/Task"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/tasks/{id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get detailed information about a specific task",
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "Get a task by ID",
                "parameters": [
                    {"type": "string", "description": "Task ID", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/Task"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "put": {
                "security": [{"BearerAuth": []}],
                "description": "Update an existing task",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "Update a task",
                "parameters": [
                    {"type": "string", "description": "Task ID", "name": "id", "in": "path", "required": true},
                    {"description": "Updated task data", "name": "task", "in": "body", "required": true, "schema": {"$ref": "#/definitions/CreateTaskRequest"}}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/Task"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "description": "Delete a task",
                "tags": ["tasks"],
                "summary": "Delete a task",
                "parameters": [
                    {"type": "string", "description": "Task ID", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "204": {"description": "No Content"},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/tasks/{id}/similar": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Find tasks similar to the specified task using vector similarity",
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "Get similar tasks",
                "parameters": [
                    {"type": "string", "description": "Task ID", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "array", "items": {"$ref": "#/definitions/SimilarTask"}}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/tasks/{id}/acknowledge": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Acknowledge a task to confirm understanding of historical context",
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "Acknowledge a task",
                "parameters": [
                    {"type": "string", "description": "Task ID", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/Task"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/tasks/{id}/start": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Start work on an acknowledged task",
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "Start a task",
                "parameters": [
                    {"type": "string", "description": "Task ID", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/Task"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/tasks/{id}/complete": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Mark a task as complete, moving it to pending review",
                "produces": ["application/json"],
                "tags": ["tasks"],
                "summary": "Complete a task",
                "parameters": [
                    {"type": "string", "description": "Task ID", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/Task"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/tasks/{id}/links": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "List all links associated with a task",
                "produces": ["application/json"],
                "tags": ["links"],
                "summary": "List task links",
                "parameters": [
                    {"type": "string", "description": "Task ID", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "array", "items": {"$ref": "#/definitions/TaskLink"}}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Create a link between two tasks",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["links"],
                "summary": "Create a task link",
                "parameters": [
                    {"type": "string", "description": "Source Task ID", "name": "id", "in": "path", "required": true},
                    {"description": "Link details", "name": "link", "in": "body", "required": true}
                ],
                "responses": {
                    "201": {"description": "Created", "schema": {"$ref": "#/definitions/TaskLink"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/tasks/{id}/blockers": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "List all blockers for a task",
                "produces": ["application/json"],
                "tags": ["blockers"],
                "summary": "List task blockers",
                "parameters": [
                    {"type": "string", "description": "Task ID", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "array", "items": {"$ref": "#/definitions/Blocker"}}}
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Report a new blocker for a task",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["blockers"],
                "summary": "Create a blocker",
                "parameters": [
                    {"type": "string", "description": "Task ID", "name": "id", "in": "path", "required": true},
                    {"description": "Blocker details", "name": "blocker", "in": "body", "required": true}
                ],
                "responses": {
                    "201": {"description": "Created", "schema": {"$ref": "#/definitions/Blocker"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        }
    },
    "definitions": {
        "Task": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "title": {"type": "string"},
                "description": {"type": "string"},
                "status": {"type": "string"},
                "estimated_days": {"type": "number"},
                "predicted_days_low": {"type": "number"},
                "predicted_days_high": {"type": "number"},
                "prediction_confidence": {"type": "number"},
                "planning_quality_score": {"type": "integer"},
                "actual_days": {"type": "number"},
                "created_at": {"type": "string"},
                "started_at": {"type": "string"},
                "completed_at": {"type": "string"}
            }
        },
        "CreateTaskRequest": {
            "type": "object",
            "required": ["title", "description", "project_id"],
            "properties": {
                "title": {"type": "string", "minLength": 5, "maxLength": 500},
                "description": {"type": "string", "minLength": 50},
                "project_id": {"type": "string"},
                "estimated_days": {"type": "number"},
                "tags": {"type": "array", "items": {"type": "string"}}
            }
        },
        "TaskListResponse": {
            "type": "object",
            "properties": {
                "tasks": {"type": "array", "items": {"$ref": "#/definitions/Task"}},
                "total": {"type": "integer"},
                "page": {"type": "integer"},
                "page_size": {"type": "integer"},
                "total_pages": {"type": "integer"}
            }
        },
        "SimilarTask": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "title": {"type": "string"},
                "status": {"type": "string"},
                "similarity_score": {"type": "number"},
                "actual_days": {"type": "number"},
                "estimated_days": {"type": "number"},
                "blockers_summary": {"type": "string"},
                "lessons_learned_excerpt": {"type": "string"}
            }
        },
        "TaskLink": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "source_task_id": {"type": "string"},
                "target_task_id": {"type": "string"},
                "link_type": {"type": "string"},
                "created_at": {"type": "string"}
            }
        },
        "Blocker": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "task_id": {"type": "string"},
                "blocker_type": {"type": "string"},
                "description": {"type": "string"},
                "reported_at": {"type": "string"},
                "resolved_at": {"type": "string"},
                "days_blocked": {"type": "integer"}
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {"type": "string"},
                "details": {"type": "string"}
            }
        },
        "TaskStats": {
            "type": "object",
            "properties": {
                "total": {"type": "integer"},
                "by_status": {"type": "object"},
                "avg_days_to_complete": {"type": "number"},
                "prediction_accuracy": {"type": "number"}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "GoPlan API",
	Description:      "Task Intelligence Platform API - Prevents repeated task failures through contextual awareness",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
