// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActivityByPlan = `-- name: CountActivityByPlan :one
SELECT COUNT(*) FROM activity_log WHERE plan_id = $1
`

func (q *Queries) CountActivityByPlan(ctx context.Context, planID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityByPlan, planID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActivityByTask = `-- name: CountActivityByTask :one
SELECT COUNT(*) FROM activity_log WHERE task_id = $1
`

func (q *Queries) CountActivityByTask(ctx context.Context, taskID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityByTask, taskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActivityByWorkspace = `-- name: CountActivityByWorkspace :one
SELECT COUNT(*) FROM activity_log WHERE workspace_id = $1
`

func (q *Queries) CountActivityByWorkspace(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActivityFiltered = `-- name: CountActivityFiltered :one
SELECT COUNT(*) FROM activity_log al
WHERE ($1::uuid IS NULL OR al.workspace_id = $1)
  AND ($2::uuid IS NULL OR al.plan_id = $2)
  AND ($3::uuid IS NULL OR al.task_id = $3)
  AND ($4::uuid IS NULL OR al.user_id = $4)
  AND ($5::varchar IS NULL OR al.action = $5)
  AND ($6::timestamptz IS NULL OR al.created_at >= $6)
  AND ($7::timestamptz IS NULL OR al.created_at <= $7)
`

type CountActivityFilteredParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	PlanID      pgtype.UUID        `json:"plan_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Action      pgtype.Text        `json:"action"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

func (q *Queries) CountActivityFiltered(ctx context.Context, arg CountActivityFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityFiltered,
		arg.WorkspaceID,
		arg.PlanID,
		arg.TaskID,
		arg.UserID,
		arg.Action,
		arg.Since,
		arg.Until,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :one
INSERT INTO activity_log (workspace_id, plan_id, task_id, user_id, action, details)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, plan_id, task_id, user_id, action, details, created_at
`

type CreateActivityLogParams struct {
	WorkspaceID string      `json:"workspace_id"`
	PlanID      pgtype.UUID `json:"plan_id"`
	TaskID      pgtype.UUID `json:"task_id"`
	UserID      string      `json:"user_id"`
	Action      string      `json:"action"`
	Details     []byte      `json:"details"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.WorkspaceID,
		arg.PlanID,
		arg.TaskID,
		arg.UserID,
		arg.Action,
		arg.Details,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PlanID,
		&i.TaskID,
		&i.UserID,
		&i.Action,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentActivity = `-- name: GetRecentActivity :many
SELECT al.id, al.workspace_id, al.plan_id, al.task_id, al.user_id, al.action, al.details, al.created_at, u.name as user_name, u.email as user_email
FROM activity_log al
JOIN users u ON al.user_id = u.id
WHERE al.user_id = $1
ORDER BY al.created_at DESC
LIMIT $2
`

type GetRecentActivityParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

type GetRecentActivityRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	PlanID      pgtype.UUID        `json:"plan_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	UserID      string             `json:"user_id"`
	Action      string             `json:"action"`
	Details     []byte             `json:"details"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UserName    string             `json:"user_name"`
	UserEmail   string             `json:"user_email"`
}

func (q *Queries) GetRecentActivity(ctx context.Context, arg GetRecentActivityParams) ([]GetRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, getRecentActivity, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentActivityRow{}
	for rows.Next() {
		var i GetRecentActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PlanID,
			&i.TaskID,
			&i.UserID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityByPlan = `-- name: ListActivityByPlan :many
SELECT al.id, al.workspace_id, al.plan_id, al.task_id, al.user_id, al.action, al.details, al.created_at, u.name as user_name, u.email as user_email
FROM activity_log al
JOIN users u ON al.user_id = u.id
WHERE al.plan_id = $1
ORDER BY al.created_at DESC
LIMIT $2 OFFSET $3
`

type ListActivityByPlanParams struct {
	PlanID pgtype.UUID `json:"plan_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListActivityByPlanRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	PlanID      pgtype.UUID        `json:"plan_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	UserID      string             `json:"user_id"`
	Action      string             `json:"action"`
	Details     []byte             `json:"details"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UserName    string             `json:"user_name"`
	UserEmail   string             `json:"user_email"`
}

func (q *Queries) ListActivityByPlan(ctx context.Context, arg ListActivityByPlanParams) ([]ListActivityByPlanRow, error) {
	rows, err := q.db.Query(ctx, listActivityByPlan, arg.PlanID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityByPlanRow{}
	for rows.Next() {
		var i ListActivityByPlanRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PlanID,
			&i.TaskID,
			&i.UserID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityByTask = `-- name: ListActivityByTask :many
SELECT al.id, al.workspace_id, al.plan_id, al.task_id, al.user_id, al.action, al.details, al.created_at, u.name as user_name, u.email as user_email
FROM activity_log al
JOIN users u ON al.user_id = u.id
WHERE al.task_id = $1
ORDER BY al.created_at DESC
LIMIT $2 OFFSET $3
`

type ListActivityByTaskParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListActivityByTaskRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	PlanID      pgtype.UUID        `json:"plan_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	UserID      string             `json:"user_id"`
	Action      string             `json:"action"`
	Details     []byte             `json:"details"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UserName    string             `json:"user_name"`
	UserEmail   string             `json:"user_email"`
}

func (q *Queries) ListActivityByTask(ctx context.Context, arg ListActivityByTaskParams) ([]ListActivityByTaskRow, error) {
	rows, err := q.db.Query(ctx, listActivityByTask, arg.TaskID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityByTaskRow{}
	for rows.Next() {
		var i ListActivityByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PlanID,
			&i.TaskID,
			&i.UserID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityByWorkspace = `-- name: ListActivityByWorkspace :many
SELECT al.id, al.workspace_id, al.plan_id, al.task_id, al.user_id, al.action, al.details, al.created_at, u.name as user_name, u.email as user_email
FROM activity_log al
JOIN users u ON al.user_id = u.id
WHERE al.workspace_id = $1
ORDER BY al.created_at DESC
LIMIT $2 OFFSET $3
`

type ListActivityByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

type ListActivityByWorkspaceRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	PlanID      pgtype.UUID        `json:"plan_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	UserID      string             `json:"user_id"`
	Action      string             `json:"action"`
	Details     []byte             `json:"details"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UserName    string             `json:"user_name"`
	UserEmail   string             `json:"user_email"`
}

func (q *Queries) ListActivityByWorkspace(ctx context.Context, arg ListActivityByWorkspaceParams) ([]ListActivityByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listActivityByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityByWorkspaceRow{}
	for rows.Next() {
		var i ListActivityByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PlanID,
			&i.TaskID,
			&i.UserID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityFiltered = `-- name: ListActivityFiltered :many
SELECT al.id, al.workspace_id, al.plan_id, al.task_id, al.user_id, al.action, al.details, al.created_at, u.name as user_name, u.email as user_email
FROM activity_log al
JOIN users u ON al.user_id = u.id
WHERE ($3::uuid IS NULL OR al.workspace_id = $3)
  AND ($4::uuid IS NULL OR al.plan_id = $4)
  AND ($5::uuid IS NULL OR al.task_id = $5)
  AND ($6::uuid IS NULL OR al.user_id = $6)
  AND ($7::varchar IS NULL OR al.action = $7)
  AND ($8::timestamptz IS NULL OR al.created_at >= $8)
  AND ($9::timestamptz IS NULL OR al.created_at <= $9)
ORDER BY al.created_at DESC
LIMIT $1 OFFSET $2
`

type ListActivityFilteredParams struct {
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	PlanID      pgtype.UUID        `json:"plan_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Action      pgtype.Text        `json:"action"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListActivityFilteredRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	PlanID      pgtype.UUID        `json:"plan_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	UserID      string             `json:"user_id"`
	Action      string             `json:"action"`
	Details     []byte             `json:"details"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UserName    string             `json:"user_name"`
	UserEmail   string             `json:"user_email"`
}

func (q *Queries) ListActivityFiltered(ctx context.Context, arg ListActivityFilteredParams) ([]ListActivityFilteredRow, error) {
	rows, err := q.db.Query(ctx, listActivityFiltered,
		arg.Limit,
		arg.Offset,
		arg.WorkspaceID,
		arg.PlanID,
		arg.TaskID,
		arg.UserID,
		arg.Action,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityFilteredRow{}
	for rows.Next() {
		var i ListActivityFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PlanID,
			&i.TaskID,
			&i.UserID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
