// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentsByTask = `-- name: CountCommentsByTask :one
SELECT COUNT(*) FROM comments WHERE task_id = $1
`

func (q *Queries) CountCommentsByTask(ctx context.Context, taskID string) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByTask, taskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (task_id, user_id, content, mentions)
VALUES ($1, $2, $3, $4)
RETURNING id, task_id, user_id, content, mentions, created_at, updated_at
`

type CreateCommentParams struct {
	TaskID   string   `json:"task_id"`
	UserID   string   `json:"user_id"`
	Content  string   `json:"content"`
	Mentions []string `json:"mentions"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.TaskID,
		arg.UserID,
		arg.Content,
		arg.Mentions,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.Content,
		&i.Mentions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT c.id, c.task_id, c.user_id, c.content, c.mentions, c.created_at, c.updated_at, u.name as user_name, u.email as user_email, u.avatar_url as user_avatar
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.id = $1
`

type GetCommentByIDRow struct {
	ID         string             `json:"id"`
	TaskID     string             `json:"task_id"`
	UserID     string             `json:"user_id"`
	Content    string             `json:"content"`
	Mentions   []string           `json:"mentions"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UserName   string             `json:"user_name"`
	UserEmail  string             `json:"user_email"`
	UserAvatar pgtype.Text        `json:"user_avatar"`
}

func (q *Queries) GetCommentByID(ctx context.Context, id string) (GetCommentByIDRow, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.Content,
		&i.Mentions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
		&i.UserAvatar,
	)
	return i, err
}

const listCommentsByTask = `-- name: ListCommentsByTask :many
SELECT c.id, c.task_id, c.user_id, c.content, c.mentions, c.created_at, c.updated_at, u.name as user_name, u.email as user_email, u.avatar_url as user_avatar
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.task_id = $1
ORDER BY c.created_at ASC
`

type ListCommentsByTaskRow struct {
	ID         string             `json:"id"`
	TaskID     string             `json:"task_id"`
	UserID     string             `json:"user_id"`
	Content    string             `json:"content"`
	Mentions   []string           `json:"mentions"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UserName   string             `json:"user_name"`
	UserEmail  string             `json:"user_email"`
	UserAvatar pgtype.Text        `json:"user_avatar"`
}

func (q *Queries) ListCommentsByTask(ctx context.Context, taskID string) ([]ListCommentsByTaskRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByTaskRow{}
	for rows.Next() {
		var i ListCommentsByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.Content,
			&i.Mentions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByTaskPaginated = `-- name: ListCommentsByTaskPaginated :many
SELECT c.id, c.task_id, c.user_id, c.content, c.mentions, c.created_at, c.updated_at, u.name as user_name, u.email as user_email, u.avatar_url as user_avatar
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.task_id = $1
ORDER BY c.created_at ASC
LIMIT $2 OFFSET $3
`

type ListCommentsByTaskPaginatedParams struct {
	TaskID string `json:"task_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListCommentsByTaskPaginatedRow struct {
	ID         string             `json:"id"`
	TaskID     string             `json:"task_id"`
	UserID     string             `json:"user_id"`
	Content    string             `json:"content"`
	Mentions   []string           `json:"mentions"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UserName   string             `json:"user_name"`
	UserEmail  string             `json:"user_email"`
	UserAvatar pgtype.Text        `json:"user_avatar"`
}

func (q *Queries) ListCommentsByTaskPaginated(ctx context.Context, arg ListCommentsByTaskPaginatedParams) ([]ListCommentsByTaskPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByTaskPaginated, arg.TaskID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByTaskPaginatedRow{}
	for rows.Next() {
		var i ListCommentsByTaskPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.Content,
			&i.Mentions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET content = $2, mentions = $3
WHERE id = $1
RETURNING id, task_id, user_id, content, mentions, created_at, updated_at
`

type UpdateCommentParams struct {
	ID       string   `json:"id"`
	Content  string   `json:"content"`
	Mentions []string `json:"mentions"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content, arg.Mentions)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.Content,
		&i.Mentions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
