// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: milestones.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMilestonesByPlan = `-- name: CountMilestonesByPlan :one
SELECT COUNT(*) FROM milestones WHERE plan_id = $1
`

func (q *Queries) CountMilestonesByPlan(ctx context.Context, planID string) (int64, error) {
	row := q.db.QueryRow(ctx, countMilestonesByPlan, planID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMilestone = `-- name: CreateMilestone :one
INSERT INTO milestones (plan_id, name, description, due_date, status, linked_task_ids)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, plan_id, name, description, due_date, status, linked_task_ids, created_at, updated_at
`

type CreateMilestoneParams struct {
	PlanID        string      `json:"plan_id"`
	Name          string      `json:"name"`
	Description   pgtype.Text `json:"description"`
	DueDate       pgtype.Date `json:"due_date"`
	Status        pgtype.Text `json:"status"`
	LinkedTaskIds []string    `json:"linked_task_ids"`
}

func (q *Queries) CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, createMilestone,
		arg.PlanID,
		arg.Name,
		arg.Description,
		arg.DueDate,
		arg.Status,
		arg.LinkedTaskIds,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Description,
		&i.DueDate,
		&i.Status,
		&i.LinkedTaskIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMilestone = `-- name: DeleteMilestone :exec
DELETE FROM milestones WHERE id = $1
`

func (q *Queries) DeleteMilestone(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMilestone, id)
	return err
}

const getMilestoneByID = `-- name: GetMilestoneByID :one
SELECT id, plan_id, name, description, due_date, status, linked_task_ids, created_at, updated_at FROM milestones WHERE id = $1
`

func (q *Queries) GetMilestoneByID(ctx context.Context, id string) (Milestone, error) {
	row := q.db.QueryRow(ctx, getMilestoneByID, id)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Description,
		&i.DueDate,
		&i.Status,
		&i.LinkedTaskIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOverdueMilestones = `-- name: GetOverdueMilestones :many
SELECT id, plan_id, name, description, due_date, status, linked_task_ids, created_at, updated_at FROM milestones
WHERE plan_id = $1
  AND due_date < CURRENT_DATE
  AND status != 'completed'
ORDER BY due_date ASC
`

func (q *Queries) GetOverdueMilestones(ctx context.Context, planID string) ([]Milestone, error) {
	rows, err := q.db.Query(ctx, getOverdueMilestones, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Milestone{}
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.Description,
			&i.DueDate,
			&i.Status,
			&i.LinkedTaskIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingMilestones = `-- name: GetUpcomingMilestones :many
SELECT id, plan_id, name, description, due_date, status, linked_task_ids, created_at, updated_at FROM milestones
WHERE plan_id = $1
  AND due_date >= CURRENT_DATE
  AND status != 'completed'
ORDER BY due_date ASC
LIMIT $2
`

type GetUpcomingMilestonesParams struct {
	PlanID string `json:"plan_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetUpcomingMilestones(ctx context.Context, arg GetUpcomingMilestonesParams) ([]Milestone, error) {
	rows, err := q.db.Query(ctx, getUpcomingMilestones, arg.PlanID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Milestone{}
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.Description,
			&i.DueDate,
			&i.Status,
			&i.LinkedTaskIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkTasksToMilestone = `-- name: LinkTasksToMilestone :one
UPDATE milestones
SET linked_task_ids = $2
WHERE id = $1
RETURNING id, plan_id, name, description, due_date, status, linked_task_ids, created_at, updated_at
`

type LinkTasksToMilestoneParams struct {
	ID            string   `json:"id"`
	LinkedTaskIds []string `json:"linked_task_ids"`
}

func (q *Queries) LinkTasksToMilestone(ctx context.Context, arg LinkTasksToMilestoneParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, linkTasksToMilestone, arg.ID, arg.LinkedTaskIds)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Description,
		&i.DueDate,
		&i.Status,
		&i.LinkedTaskIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMilestonesByPlan = `-- name: ListMilestonesByPlan :many
SELECT id, plan_id, name, description, due_date, status, linked_task_ids, created_at, updated_at FROM milestones WHERE plan_id = $1 ORDER BY due_date ASC
`

func (q *Queries) ListMilestonesByPlan(ctx context.Context, planID string) ([]Milestone, error) {
	rows, err := q.db.Query(ctx, listMilestonesByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Milestone{}
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.Description,
			&i.DueDate,
			&i.Status,
			&i.LinkedTaskIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMilestone = `-- name: UpdateMilestone :one
UPDATE milestones
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    due_date = COALESCE($4, due_date),
    status = COALESCE($5, status),
    linked_task_ids = COALESCE($6, linked_task_ids)
WHERE id = $1
RETURNING id, plan_id, name, description, due_date, status, linked_task_ids, created_at, updated_at
`

type UpdateMilestoneParams struct {
	ID            string      `json:"id"`
	Name          pgtype.Text `json:"name"`
	Description   pgtype.Text `json:"description"`
	DueDate       pgtype.Date `json:"due_date"`
	Status        pgtype.Text `json:"status"`
	LinkedTaskIds []string    `json:"linked_task_ids"`
}

func (q *Queries) UpdateMilestone(ctx context.Context, arg UpdateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, updateMilestone,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DueDate,
		arg.Status,
		arg.LinkedTaskIds,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Description,
		&i.DueDate,
		&i.Status,
		&i.LinkedTaskIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMilestoneStatus = `-- name: UpdateMilestoneStatus :one
UPDATE milestones SET status = $2 WHERE id = $1 RETURNING id, plan_id, name, description, due_date, status, linked_task_ids, created_at, updated_at
`

type UpdateMilestoneStatusParams struct {
	ID     string      `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateMilestoneStatus(ctx context.Context, arg UpdateMilestoneStatusParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, updateMilestoneStatus, arg.ID, arg.Status)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Description,
		&i.DueDate,
		&i.Status,
		&i.LinkedTaskIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
