// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLog struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	PlanID      pgtype.UUID        `json:"plan_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	UserID      string             `json:"user_id"`
	Action      string             `json:"action"`
	Details     []byte             `json:"details"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AiSuggestion struct {
	ID             string             `json:"id"`
	WorkspaceID    string             `json:"workspace_id"`
	PlanID         pgtype.UUID        `json:"plan_id"`
	TaskID         pgtype.UUID        `json:"task_id"`
	UserID         string             `json:"user_id"`
	SuggestionType string             `json:"suggestion_type"`
	Content        json.RawMessage    `json:"content"`
	Status         pgtype.Text        `json:"status"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
	RejectedAt     pgtype.Timestamptz `json:"rejected_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Comment struct {
	ID        string             `json:"id"`
	TaskID    string             `json:"task_id"`
	UserID    string             `json:"user_id"`
	Content   string             `json:"content"`
	Mentions  []string           `json:"mentions"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type McpAuditLog struct {
	ID              string             `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	UserID          string             `json:"user_id"`
	SessionID       pgtype.Text        `json:"session_id"`
	RequestType     string             `json:"request_type"`
	RequestPayload  []byte             `json:"request_payload"`
	ResponsePayload []byte             `json:"response_payload"`
	Model           pgtype.Text        `json:"model"`
	TokensUsed      pgtype.Int4        `json:"tokens_used"`
	LatencyMs       pgtype.Int4        `json:"latency_ms"`
	Status          string             `json:"status"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Milestone struct {
	ID            string             `json:"id"`
	PlanID        string             `json:"plan_id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	DueDate       pgtype.Date        `json:"due_date"`
	Status        pgtype.Text        `json:"status"`
	LinkedTaskIds []string           `json:"linked_task_ids"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Phase struct {
	ID          string             `json:"id"`
	PlanID      string             `json:"plan_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Order       pgtype.Int4        `json:"order"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Plan struct {
	ID             string             `json:"id"`
	WorkspaceID    string             `json:"workspace_id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	Domain         string             `json:"domain"`
	Status         string             `json:"status"`
	OwnerID        string             `json:"owner_id"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	CustomStatuses []byte             `json:"custom_statuses"`
	CustomFields   []byte             `json:"custom_fields"`
	Tags           []string           `json:"tags"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Task struct {
	ID                string             `json:"id"`
	PlanID            string             `json:"plan_id"`
	PhaseID           pgtype.UUID        `json:"phase_id"`
	ParentID          pgtype.UUID        `json:"parent_id"`
	Title             string             `json:"title"`
	Description       pgtype.Text        `json:"description"`
	Status            string             `json:"status"`
	Priority          pgtype.Text        `json:"priority"`
	AssigneeID        pgtype.UUID        `json:"assignee_id"`
	DueDate           pgtype.Date        `json:"due_date"`
	EstimatedHours    pgtype.Numeric     `json:"estimated_hours"`
	CustomFieldValues []byte             `json:"custom_field_values"`
	Tags              []string           `json:"tags"`
	Position          pgtype.Int4        `json:"position"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type TaskDependency struct {
	TaskID      string `json:"task_id"`
	DependsOnID string `json:"depends_on_id"`
}

type User struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	OwnerID   string             `json:"owner_id"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceMember struct {
	WorkspaceID string             `json:"workspace_id"`
	UserID      string             `json:"user_id"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}
