// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: phases.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPhasesByPlan = `-- name: CountPhasesByPlan :one
SELECT COUNT(*) FROM phases WHERE plan_id = $1
`

func (q *Queries) CountPhasesByPlan(ctx context.Context, planID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPhasesByPlan, planID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPhase = `-- name: CreatePhase :one
INSERT INTO phases (plan_id, name, description, "order", start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, plan_id, name, description, "order", start_date, end_date, created_at, updated_at
`

type CreatePhaseParams struct {
	PlanID      string      `json:"plan_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Order       pgtype.Int4 `json:"order"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

func (q *Queries) CreatePhase(ctx context.Context, arg CreatePhaseParams) (Phase, error) {
	row := q.db.QueryRow(ctx, createPhase,
		arg.PlanID,
		arg.Name,
		arg.Description,
		arg.Order,
		arg.StartDate,
		arg.EndDate,
	)
	var i Phase
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Description,
		&i.Order,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePhase = `-- name: DeletePhase :exec
DELETE FROM phases WHERE id = $1
`

func (q *Queries) DeletePhase(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePhase, id)
	return err
}

const getMaxPhaseOrder = `-- name: GetMaxPhaseOrder :one
SELECT COALESCE(MAX("order"), -1)::integer FROM phases WHERE plan_id = $1
`

func (q *Queries) GetMaxPhaseOrder(ctx context.Context, planID string) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxPhaseOrder, planID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getPhaseByID = `-- name: GetPhaseByID :one
SELECT id, plan_id, name, description, "order", start_date, end_date, created_at, updated_at FROM phases WHERE id = $1
`

func (q *Queries) GetPhaseByID(ctx context.Context, id string) (Phase, error) {
	row := q.db.QueryRow(ctx, getPhaseByID, id)
	var i Phase
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Description,
		&i.Order,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPhasesByPlan = `-- name: ListPhasesByPlan :many
SELECT id, plan_id, name, description, "order", start_date, end_date, created_at, updated_at FROM phases WHERE plan_id = $1 ORDER BY "order" ASC
`

func (q *Queries) ListPhasesByPlan(ctx context.Context, planID string) ([]Phase, error) {
	rows, err := q.db.Query(ctx, listPhasesByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Phase{}
	for rows.Next() {
		var i Phase
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.Description,
			&i.Order,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderPhases = `-- name: ReorderPhases :exec
UPDATE phases
SET "order" = data.new_order
FROM (
    SELECT unnest($1::uuid[]) AS phase_id,
           generate_series(0, array_length($1::uuid[], 1) - 1) AS new_order
) AS data
WHERE phases.id = data.phase_id
`

func (q *Queries) ReorderPhases(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, reorderPhases, dollar_1)
	return err
}

const updatePhase = `-- name: UpdatePhase :one
UPDATE phases
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    "order" = COALESCE($4, "order"),
    start_date = COALESCE($5, start_date),
    end_date = COALESCE($6, end_date)
WHERE id = $1
RETURNING id, plan_id, name, description, "order", start_date, end_date, created_at, updated_at
`

type UpdatePhaseParams struct {
	ID          string      `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	Order       pgtype.Int4 `json:"order"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

func (q *Queries) UpdatePhase(ctx context.Context, arg UpdatePhaseParams) (Phase, error) {
	row := q.db.QueryRow(ctx, updatePhase,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Order,
		arg.StartDate,
		arg.EndDate,
	)
	var i Phase
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Description,
		&i.Order,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
