// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlansByWorkspace = `-- name: CountPlansByWorkspace :one
SELECT COUNT(*) FROM plans WHERE workspace_id = $1
`

func (q *Queries) CountPlansByWorkspace(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPlansByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlansByWorkspaceFiltered = `-- name: CountPlansByWorkspaceFiltered :one
SELECT COUNT(*) FROM plans
WHERE workspace_id = $1
  AND ($2::varchar IS NULL OR status = $2)
  AND ($3::uuid IS NULL OR owner_id = $3)
  AND ($4::varchar IS NULL OR domain = $4)
`

type CountPlansByWorkspaceFilteredParams struct {
	WorkspaceID string      `json:"workspace_id"`
	Status      pgtype.Text `json:"status"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	Domain      pgtype.Text `json:"domain"`
}

func (q *Queries) CountPlansByWorkspaceFiltered(ctx context.Context, arg CountPlansByWorkspaceFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPlansByWorkspaceFiltered,
		arg.WorkspaceID,
		arg.Status,
		arg.OwnerID,
		arg.Domain,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
    workspace_id, name, description, domain, status,
    owner_id, start_date, end_date, custom_statuses, custom_fields, tags
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, workspace_id, name, description, domain, status, owner_id, start_date, end_date, custom_statuses, custom_fields, tags, created_at, updated_at
`

type CreatePlanParams struct {
	WorkspaceID    string      `json:"workspace_id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	Domain         string      `json:"domain"`
	Status         string      `json:"status"`
	OwnerID        string      `json:"owner_id"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
	CustomStatuses []byte      `json:"custom_statuses"`
	CustomFields   []byte      `json:"custom_fields"`
	Tags           []string    `json:"tags"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Domain,
		arg.Status,
		arg.OwnerID,
		arg.StartDate,
		arg.EndDate,
		arg.CustomStatuses,
		arg.CustomFields,
		arg.Tags,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Domain,
		&i.Status,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.CustomStatuses,
		&i.CustomFields,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE id = $1
`

func (q *Queries) DeletePlan(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePlan, id)
	return err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, workspace_id, name, description, domain, status, owner_id, start_date, end_date, custom_statuses, custom_fields, tags, created_at, updated_at FROM plans WHERE id = $1
`

func (q *Queries) GetPlanByID(ctx context.Context, id string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Domain,
		&i.Status,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.CustomStatuses,
		&i.CustomFields,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlansByOwner = `-- name: GetPlansByOwner :many
SELECT id, workspace_id, name, description, domain, status, owner_id, start_date, end_date, custom_statuses, custom_fields, tags, created_at, updated_at FROM plans WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetPlansByOwner(ctx context.Context, ownerID string) ([]Plan, error) {
	rows, err := q.db.Query(ctx, getPlansByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Domain,
			&i.Status,
			&i.OwnerID,
			&i.StartDate,
			&i.EndDate,
			&i.CustomStatuses,
			&i.CustomFields,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansByWorkspace = `-- name: ListPlansByWorkspace :many
SELECT id, workspace_id, name, description, domain, status, owner_id, start_date, end_date, custom_statuses, custom_fields, tags, created_at, updated_at FROM plans
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPlansByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListPlansByWorkspace(ctx context.Context, arg ListPlansByWorkspaceParams) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlansByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Domain,
			&i.Status,
			&i.OwnerID,
			&i.StartDate,
			&i.EndDate,
			&i.CustomStatuses,
			&i.CustomFields,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansByWorkspaceFiltered = `-- name: ListPlansByWorkspaceFiltered :many
SELECT id, workspace_id, name, description, domain, status, owner_id, start_date, end_date, custom_statuses, custom_fields, tags, created_at, updated_at FROM plans
WHERE workspace_id = $1
  AND ($4::varchar IS NULL OR status = $4)
  AND ($5::uuid IS NULL OR owner_id = $5)
  AND ($6::varchar IS NULL OR domain = $6)
ORDER BY
  CASE WHEN $7::varchar = 'name' AND $8::varchar = 'ASC' THEN name END ASC,
  CASE WHEN $7::varchar = 'name' AND $8::varchar = 'DESC' THEN name END DESC,
  CASE WHEN $7::varchar = 'created_at' AND $8::varchar = 'ASC' THEN created_at END ASC,
  CASE WHEN $7::varchar = 'updated_at' AND $8::varchar = 'ASC' THEN updated_at END ASC,
  CASE WHEN $7::varchar = 'updated_at' AND $8::varchar = 'DESC' THEN updated_at END DESC,
  created_at DESC
LIMIT $2 OFFSET $3
`

type ListPlansByWorkspaceFilteredParams struct {
	WorkspaceID string      `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	Status      pgtype.Text `json:"status"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	Domain      pgtype.Text `json:"domain"`
	SortField   pgtype.Text `json:"sort_field"`
	SortOrder   pgtype.Text `json:"sort_order"`
}

func (q *Queries) ListPlansByWorkspaceFiltered(ctx context.Context, arg ListPlansByWorkspaceFilteredParams) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlansByWorkspaceFiltered,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.OwnerID,
		arg.Domain,
		arg.SortField,
		arg.SortOrder,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Domain,
			&i.Status,
			&i.OwnerID,
			&i.StartDate,
			&i.EndDate,
			&i.CustomStatuses,
			&i.CustomFields,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    domain = COALESCE($4, domain),
    status = COALESCE($5, status),
    start_date = COALESCE($6, start_date),
    end_date = COALESCE($7, end_date),
    custom_statuses = COALESCE($8, custom_statuses),
    custom_fields = COALESCE($9, custom_fields),
    tags = COALESCE($10, tags)
WHERE id = $1
RETURNING id, workspace_id, name, description, domain, status, owner_id, start_date, end_date, custom_statuses, custom_fields, tags, created_at, updated_at
`

type UpdatePlanParams struct {
	ID             string      `json:"id"`
	Name           pgtype.Text `json:"name"`
	Description    pgtype.Text `json:"description"`
	Domain         pgtype.Text `json:"domain"`
	Status         pgtype.Text `json:"status"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
	CustomStatuses []byte      `json:"custom_statuses"`
	CustomFields   []byte      `json:"custom_fields"`
	Tags           []string    `json:"tags"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Domain,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.CustomStatuses,
		arg.CustomFields,
		arg.Tags,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Domain,
		&i.Status,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.CustomStatuses,
		&i.CustomFields,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlanStatus = `-- name: UpdatePlanStatus :one
UPDATE plans SET status = $2 WHERE id = $1 RETURNING id, workspace_id, name, description, domain, status, owner_id, start_date, end_date, custom_statuses, custom_fields, tags, created_at, updated_at
`

type UpdatePlanStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdatePlanStatus(ctx context.Context, arg UpdatePlanStatusParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlanStatus, arg.ID, arg.Status)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Domain,
		&i.Status,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.CustomStatuses,
		&i.CustomFields,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
