// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Add dependency
	AddTaskDependency(ctx context.Context, arg AddTaskDependencyParams) error
	AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error
	CountActivityByPlan(ctx context.Context, planID pgtype.UUID) (int64, error)
	CountActivityByTask(ctx context.Context, taskID pgtype.UUID) (int64, error)
	CountActivityByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountActivityFiltered(ctx context.Context, arg CountActivityFilteredParams) (int64, error)
	CountCommentsByTask(ctx context.Context, taskID string) (int64, error)
	CountMilestonesByPlan(ctx context.Context, planID string) (int64, error)
	CountPhasesByPlan(ctx context.Context, planID string) (int64, error)
	CountPlansByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountPlansByWorkspaceFiltered(ctx context.Context, arg CountPlansByWorkspaceFilteredParams) (int64, error)
	CountSearchTasks(ctx context.Context, arg CountSearchTasksParams) (int64, error)
	CountTasksByPlan(ctx context.Context, planID string) (int64, error)
	CountTasksByPlanFiltered(ctx context.Context, arg CountTasksByPlanFilteredParams) (int64, error)
	CountTasksByStatus(ctx context.Context, planID string) ([]CountTasksByStatusRow, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWorkspaceMembers(ctx context.Context, workspaceID string) (int64, error)
	CountWorkspaces(ctx context.Context) (int64, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (Milestone, error)
	CreatePhase(ctx context.Context, arg CreatePhaseParams) (Phase, error)
	CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteComment(ctx context.Context, id string) error
	DeleteMilestone(ctx context.Context, id string) error
	DeletePhase(ctx context.Context, id string) error
	DeletePlan(ctx context.Context, id string) error
	DeleteTask(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteWorkspace(ctx context.Context, id string) error
	ExistsByEmail(ctx context.Context, email string) (bool, error)
	ExistsBySlug(ctx context.Context, slug string) (bool, error)
	GetCommentByID(ctx context.Context, id string) (GetCommentByIDRow, error)
	GetMaxPhaseOrder(ctx context.Context, planID string) (int32, error)
	GetMaxTaskPosition(ctx context.Context, planID string) (int32, error)
	GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error)
	GetMilestoneByID(ctx context.Context, id string) (Milestone, error)
	GetOverdueMilestones(ctx context.Context, planID string) ([]Milestone, error)
	GetOverdueTasks(ctx context.Context, planID string) ([]Task, error)
	GetPhaseByID(ctx context.Context, id string) (Phase, error)
	GetPlanByID(ctx context.Context, id string) (Plan, error)
	GetPlansByOwner(ctx context.Context, ownerID string) ([]Plan, error)
	GetRecentActivity(ctx context.Context, arg GetRecentActivityParams) ([]GetRecentActivityRow, error)
	GetTaskByID(ctx context.Context, id string) (Task, error)
	// Get task dependencies (tasks this task depends on)
	GetTaskDependencies(ctx context.Context, taskID string) ([]Task, error)
	// Get tasks that depend on this task
	GetTaskDependents(ctx context.Context, dependsOnID string) ([]Task, error)
	GetTasksForKanban(ctx context.Context, planID string) ([]Task, error)
	GetUpcomingMilestones(ctx context.Context, arg GetUpcomingMilestonesParams) ([]Milestone, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserWorkspaces(ctx context.Context, userID string) ([]GetUserWorkspacesRow, error)
	GetUsersByIDs(ctx context.Context, dollar_1 []string) ([]User, error)
	GetWorkspaceByID(ctx context.Context, id string) (Workspace, error)
	GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error)
	GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (GetWorkspaceMemberRow, error)
	// Check if dependency would create a cycle
	HasDependency(ctx context.Context, arg HasDependencyParams) (bool, error)
	IsMember(ctx context.Context, arg IsMemberParams) (bool, error)
	LinkTasksToMilestone(ctx context.Context, arg LinkTasksToMilestoneParams) (Milestone, error)
	ListActivityByPlan(ctx context.Context, arg ListActivityByPlanParams) ([]ListActivityByPlanRow, error)
	ListActivityByTask(ctx context.Context, arg ListActivityByTaskParams) ([]ListActivityByTaskRow, error)
	ListActivityByWorkspace(ctx context.Context, arg ListActivityByWorkspaceParams) ([]ListActivityByWorkspaceRow, error)
	ListActivityFiltered(ctx context.Context, arg ListActivityFilteredParams) ([]ListActivityFilteredRow, error)
	ListCommentsByTask(ctx context.Context, taskID string) ([]ListCommentsByTaskRow, error)
	ListCommentsByTaskPaginated(ctx context.Context, arg ListCommentsByTaskPaginatedParams) ([]ListCommentsByTaskPaginatedRow, error)
	ListMilestonesByPlan(ctx context.Context, planID string) ([]Milestone, error)
	ListPhasesByPlan(ctx context.Context, planID string) ([]Phase, error)
	ListPlansByWorkspace(ctx context.Context, arg ListPlansByWorkspaceParams) ([]Plan, error)
	ListPlansByWorkspaceFiltered(ctx context.Context, arg ListPlansByWorkspaceFilteredParams) ([]Plan, error)
	ListSubtasks(ctx context.Context, parentID pgtype.UUID) ([]Task, error)
	ListTasksByPlan(ctx context.Context, arg ListTasksByPlanParams) ([]Task, error)
	ListTasksByPlanFiltered(ctx context.Context, arg ListTasksByPlanFilteredParams) ([]Task, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListWorkspaceMembers(ctx context.Context, workspaceID string) ([]ListWorkspaceMembersRow, error)
	ListWorkspaces(ctx context.Context, arg ListWorkspacesParams) ([]Workspace, error)
	MoveTask(ctx context.Context, arg MoveTaskParams) (Task, error)
	// Remove dependency
	RemoveTaskDependency(ctx context.Context, arg RemoveTaskDependencyParams) error
	RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) error
	ReorderPhases(ctx context.Context, dollar_1 []string) error
	SearchTasks(ctx context.Context, arg SearchTasksParams) ([]Task, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error
	UpdateMilestone(ctx context.Context, arg UpdateMilestoneParams) (Milestone, error)
	UpdateMilestoneStatus(ctx context.Context, arg UpdateMilestoneStatusParams) (Milestone, error)
	UpdatePhase(ctx context.Context, arg UpdatePhaseParams) (Phase, error)
	UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error)
	UpdatePlanStatus(ctx context.Context, arg UpdatePlanStatusParams) (Plan, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateTaskPosition(ctx context.Context, arg UpdateTaskPositionParams) (Task, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
}

var _ Querier = (*Queries)(nil)
