// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTaskDependency = `-- name: AddTaskDependency :exec
INSERT INTO task_dependencies (task_id, depends_on_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTaskDependencyParams struct {
	TaskID      string `json:"task_id"`
	DependsOnID string `json:"depends_on_id"`
}

// Add dependency
func (q *Queries) AddTaskDependency(ctx context.Context, arg AddTaskDependencyParams) error {
	_, err := q.db.Exec(ctx, addTaskDependency, arg.TaskID, arg.DependsOnID)
	return err
}

const countSearchTasks = `-- name: CountSearchTasks :one
SELECT COUNT(*) FROM tasks
WHERE plan_id = $1
  AND to_tsvector('english', coalesce(title, '') || ' ' || coalesce(description, ''))
      @@ plainto_tsquery('english', $2)
`

type CountSearchTasksParams struct {
	PlanID         string `json:"plan_id"`
	PlaintoTsquery string `json:"plainto_tsquery"`
}

func (q *Queries) CountSearchTasks(ctx context.Context, arg CountSearchTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchTasks, arg.PlanID, arg.PlaintoTsquery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksByPlan = `-- name: CountTasksByPlan :one
SELECT COUNT(*) FROM tasks WHERE plan_id = $1
`

func (q *Queries) CountTasksByPlan(ctx context.Context, planID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksByPlan, planID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksByPlanFiltered = `-- name: CountTasksByPlanFiltered :one
SELECT COUNT(*) FROM tasks
WHERE plan_id = $1
  AND ($2::uuid IS NULL OR phase_id = $2)
  AND ($3::uuid IS NULL OR parent_id = $3)
  AND ($4::varchar IS NULL OR status = $4)
  AND ($5::varchar IS NULL OR priority = $5)
  AND ($6::uuid IS NULL OR assignee_id = $6)
  AND ($7::date IS NULL OR due_date <= $7)
  AND ($8::date IS NULL OR due_date >= $8)
`

type CountTasksByPlanFilteredParams struct {
	PlanID     string      `json:"plan_id"`
	PhaseID    pgtype.UUID `json:"phase_id"`
	ParentID   pgtype.UUID `json:"parent_id"`
	Status     pgtype.Text `json:"status"`
	Priority   pgtype.Text `json:"priority"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
	DueBefore  pgtype.Date `json:"due_before"`
	DueAfter   pgtype.Date `json:"due_after"`
}

func (q *Queries) CountTasksByPlanFiltered(ctx context.Context, arg CountTasksByPlanFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksByPlanFiltered,
		arg.PlanID,
		arg.PhaseID,
		arg.ParentID,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.DueBefore,
		arg.DueAfter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksByStatus = `-- name: CountTasksByStatus :many
SELECT status, COUNT(*) as count
FROM tasks
WHERE plan_id = $1
GROUP BY status
`

type CountTasksByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountTasksByStatus(ctx context.Context, planID string) ([]CountTasksByStatusRow, error) {
	rows, err := q.db.Query(ctx, countTasksByStatus, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTasksByStatusRow{}
	for rows.Next() {
		var i CountTasksByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    plan_id, phase_id, parent_id, title, description, status,
    priority, assignee_id, due_date, estimated_hours,
    custom_field_values, tags, position
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, plan_id, phase_id, parent_id, title, description, status, priority, assignee_id, due_date, estimated_hours, custom_field_values, tags, position, created_at, updated_at
`

type CreateTaskParams struct {
	PlanID            string         `json:"plan_id"`
	PhaseID           pgtype.UUID    `json:"phase_id"`
	ParentID          pgtype.UUID    `json:"parent_id"`
	Title             string         `json:"title"`
	Description       pgtype.Text    `json:"description"`
	Status            string         `json:"status"`
	Priority          pgtype.Text    `json:"priority"`
	AssigneeID        pgtype.UUID    `json:"assignee_id"`
	DueDate           pgtype.Date    `json:"due_date"`
	EstimatedHours    pgtype.Numeric `json:"estimated_hours"`
	CustomFieldValues []byte         `json:"custom_field_values"`
	Tags              []string       `json:"tags"`
	Position          pgtype.Int4    `json:"position"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.PlanID,
		arg.PhaseID,
		arg.ParentID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.DueDate,
		arg.EstimatedHours,
		arg.CustomFieldValues,
		arg.Tags,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PhaseID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.EstimatedHours,
		&i.CustomFieldValues,
		&i.Tags,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getMaxTaskPosition = `-- name: GetMaxTaskPosition :one
SELECT COALESCE(MAX(position), -1)::integer FROM tasks WHERE plan_id = $1
`

func (q *Queries) GetMaxTaskPosition(ctx context.Context, planID string) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxTaskPosition, planID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getOverdueTasks = `-- name: GetOverdueTasks :many
SELECT id, plan_id, phase_id, parent_id, title, description, status, priority, assignee_id, due_date, estimated_hours, custom_field_values, tags, position, created_at, updated_at FROM tasks
WHERE plan_id = $1
  AND due_date < CURRENT_DATE
  AND status NOT IN ('done', 'completed')
ORDER BY due_date ASC
`

func (q *Queries) GetOverdueTasks(ctx context.Context, planID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getOverdueTasks, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PhaseID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.EstimatedHours,
			&i.CustomFieldValues,
			&i.Tags,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, plan_id, phase_id, parent_id, title, description, status, priority, assignee_id, due_date, estimated_hours, custom_field_values, tags, position, created_at, updated_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PhaseID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.EstimatedHours,
		&i.CustomFieldValues,
		&i.Tags,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskDependencies = `-- name: GetTaskDependencies :many
SELECT t.id, t.plan_id, t.phase_id, t.parent_id, t.title, t.description, t.status, t.priority, t.assignee_id, t.due_date, t.estimated_hours, t.custom_field_values, t.tags, t.position, t.created_at, t.updated_at FROM tasks t
JOIN task_dependencies td ON t.id = td.depends_on_id
WHERE td.task_id = $1
`

// Get task dependencies (tasks this task depends on)
func (q *Queries) GetTaskDependencies(ctx context.Context, taskID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskDependencies, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PhaseID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.EstimatedHours,
			&i.CustomFieldValues,
			&i.Tags,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskDependents = `-- name: GetTaskDependents :many
SELECT t.id, t.plan_id, t.phase_id, t.parent_id, t.title, t.description, t.status, t.priority, t.assignee_id, t.due_date, t.estimated_hours, t.custom_field_values, t.tags, t.position, t.created_at, t.updated_at FROM tasks t
JOIN task_dependencies td ON t.id = td.task_id
WHERE td.depends_on_id = $1
`

// Get tasks that depend on this task
func (q *Queries) GetTaskDependents(ctx context.Context, dependsOnID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskDependents, dependsOnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PhaseID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.EstimatedHours,
			&i.CustomFieldValues,
			&i.Tags,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksForKanban = `-- name: GetTasksForKanban :many
SELECT id, plan_id, phase_id, parent_id, title, description, status, priority, assignee_id, due_date, estimated_hours, custom_field_values, tags, position, created_at, updated_at FROM tasks
WHERE plan_id = $1 AND parent_id IS NULL
ORDER BY status, position ASC
`

func (q *Queries) GetTasksForKanban(ctx context.Context, planID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksForKanban, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PhaseID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.EstimatedHours,
			&i.CustomFieldValues,
			&i.Tags,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasDependency = `-- name: HasDependency :one
SELECT EXISTS(
    SELECT 1 FROM task_dependencies
    WHERE task_id = $1 AND depends_on_id = $2
)
`

type HasDependencyParams struct {
	TaskID      string `json:"task_id"`
	DependsOnID string `json:"depends_on_id"`
}

// Check if dependency would create a cycle
func (q *Queries) HasDependency(ctx context.Context, arg HasDependencyParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasDependency, arg.TaskID, arg.DependsOnID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSubtasks = `-- name: ListSubtasks :many
SELECT id, plan_id, phase_id, parent_id, title, description, status, priority, assignee_id, due_date, estimated_hours, custom_field_values, tags, position, created_at, updated_at FROM tasks WHERE parent_id = $1 ORDER BY position ASC
`

func (q *Queries) ListSubtasks(ctx context.Context, parentID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listSubtasks, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PhaseID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.EstimatedHours,
			&i.CustomFieldValues,
			&i.Tags,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByPlan = `-- name: ListTasksByPlan :many
SELECT id, plan_id, phase_id, parent_id, title, description, status, priority, assignee_id, due_date, estimated_hours, custom_field_values, tags, position, created_at, updated_at FROM tasks
WHERE plan_id = $1
ORDER BY position ASC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListTasksByPlanParams struct {
	PlanID string `json:"plan_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListTasksByPlan(ctx context.Context, arg ListTasksByPlanParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByPlan, arg.PlanID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PhaseID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.EstimatedHours,
			&i.CustomFieldValues,
			&i.Tags,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByPlanFiltered = `-- name: ListTasksByPlanFiltered :many
SELECT id, plan_id, phase_id, parent_id, title, description, status, priority, assignee_id, due_date, estimated_hours, custom_field_values, tags, position, created_at, updated_at FROM tasks
WHERE plan_id = $1
  AND ($4::uuid IS NULL OR phase_id = $4)
  AND ($5::uuid IS NULL OR parent_id = $5)
  AND ($6::varchar IS NULL OR status = $6)
  AND ($7::varchar IS NULL OR priority = $7)
  AND ($8::uuid IS NULL OR assignee_id = $8)
  AND ($9::date IS NULL OR due_date <= $9)
  AND ($10::date IS NULL OR due_date >= $10)
ORDER BY position ASC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListTasksByPlanFilteredParams struct {
	PlanID     string      `json:"plan_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	PhaseID    pgtype.UUID `json:"phase_id"`
	ParentID   pgtype.UUID `json:"parent_id"`
	Status     pgtype.Text `json:"status"`
	Priority   pgtype.Text `json:"priority"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
	DueBefore  pgtype.Date `json:"due_before"`
	DueAfter   pgtype.Date `json:"due_after"`
}

func (q *Queries) ListTasksByPlanFiltered(ctx context.Context, arg ListTasksByPlanFilteredParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByPlanFiltered,
		arg.PlanID,
		arg.Limit,
		arg.Offset,
		arg.PhaseID,
		arg.ParentID,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.DueBefore,
		arg.DueAfter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PhaseID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.EstimatedHours,
			&i.CustomFieldValues,
			&i.Tags,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveTask = `-- name: MoveTask :one
UPDATE tasks
SET phase_id = $2, position = $3
WHERE id = $1
RETURNING id, plan_id, phase_id, parent_id, title, description, status, priority, assignee_id, due_date, estimated_hours, custom_field_values, tags, position, created_at, updated_at
`

type MoveTaskParams struct {
	ID       string      `json:"id"`
	PhaseID  pgtype.UUID `json:"phase_id"`
	Position pgtype.Int4 `json:"position"`
}

func (q *Queries) MoveTask(ctx context.Context, arg MoveTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, moveTask, arg.ID, arg.PhaseID, arg.Position)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PhaseID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.EstimatedHours,
		&i.CustomFieldValues,
		&i.Tags,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeTaskDependency = `-- name: RemoveTaskDependency :exec
DELETE FROM task_dependencies
WHERE task_id = $1 AND depends_on_id = $2
`

type RemoveTaskDependencyParams struct {
	TaskID      string `json:"task_id"`
	DependsOnID string `json:"depends_on_id"`
}

// Remove dependency
func (q *Queries) RemoveTaskDependency(ctx context.Context, arg RemoveTaskDependencyParams) error {
	_, err := q.db.Exec(ctx, removeTaskDependency, arg.TaskID, arg.DependsOnID)
	return err
}

const searchTasks = `-- name: SearchTasks :many
SELECT id, plan_id, phase_id, parent_id, title, description, status, priority, assignee_id, due_date, estimated_hours, custom_field_values, tags, position, created_at, updated_at FROM tasks
WHERE plan_id = $1
  AND to_tsvector('english', coalesce(title, '') || ' ' || coalesce(description, ''))
      @@ plainto_tsquery('english', $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type SearchTasksParams struct {
	PlanID         string `json:"plan_id"`
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) SearchTasks(ctx context.Context, arg SearchTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, searchTasks,
		arg.PlanID,
		arg.PlaintoTsquery,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PhaseID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.EstimatedHours,
			&i.CustomFieldValues,
			&i.Tags,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = COALESCE($2, title),
    description = COALESCE($3, description),
    status = COALESCE($4, status),
    priority = COALESCE($5, priority),
    phase_id = COALESCE($6, phase_id),
    assignee_id = COALESCE($7, assignee_id),
    due_date = COALESCE($8, due_date),
    estimated_hours = COALESCE($9, estimated_hours),
    custom_field_values = COALESCE($10, custom_field_values),
    tags = COALESCE($11, tags),
    position = COALESCE($12, position)
WHERE id = $1
RETURNING id, plan_id, phase_id, parent_id, title, description, status, priority, assignee_id, due_date, estimated_hours, custom_field_values, tags, position, created_at, updated_at
`

type UpdateTaskParams struct {
	ID                string         `json:"id"`
	Title             pgtype.Text    `json:"title"`
	Description       pgtype.Text    `json:"description"`
	Status            pgtype.Text    `json:"status"`
	Priority          pgtype.Text    `json:"priority"`
	PhaseID           pgtype.UUID    `json:"phase_id"`
	AssigneeID        pgtype.UUID    `json:"assignee_id"`
	DueDate           pgtype.Date    `json:"due_date"`
	EstimatedHours    pgtype.Numeric `json:"estimated_hours"`
	CustomFieldValues []byte         `json:"custom_field_values"`
	Tags              []string       `json:"tags"`
	Position          pgtype.Int4    `json:"position"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.PhaseID,
		arg.AssigneeID,
		arg.DueDate,
		arg.EstimatedHours,
		arg.CustomFieldValues,
		arg.Tags,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PhaseID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.EstimatedHours,
		&i.CustomFieldValues,
		&i.Tags,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskPosition = `-- name: UpdateTaskPosition :one
UPDATE tasks SET position = $2 WHERE id = $1 RETURNING id, plan_id, phase_id, parent_id, title, description, status, priority, assignee_id, due_date, estimated_hours, custom_field_values, tags, position, created_at, updated_at
`

type UpdateTaskPositionParams struct {
	ID       string      `json:"id"`
	Position pgtype.Int4 `json:"position"`
}

func (q *Queries) UpdateTaskPosition(ctx context.Context, arg UpdateTaskPositionParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskPosition, arg.ID, arg.Position)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PhaseID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.EstimatedHours,
		&i.CustomFieldValues,
		&i.Tags,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks SET status = $2 WHERE id = $1 RETURNING id, plan_id, phase_id, parent_id, title, description, status, priority, assignee_id, due_date, estimated_hours, custom_field_values, tags, position, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PhaseID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.EstimatedHours,
		&i.CustomFieldValues,
		&i.Tags,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
