apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goplan-production

namePrefix: prod-

resources:
  - ../../base

patches:
  - path: patches/deployment-replicas.yaml
  - path: patches/ingress-host.yaml

configMapGenerator:
  - name: goplan-config
    behavior: merge
    literals:
      - log-level=warn
      - allow-origins=https://goplan.yourcompany.com

images:
  - name: goplan/api
    newTag: v1.0.0
  - name: goplan/frontend
    newTag: v1.0.0

commonLabels:
  environment: production
